language: go
dist: trusty
sudo: false
install: true
env:
  global:
  - MYAPP=scrum-report
  - MYEMAIL=oleg.balunenko@gmail.com
  - secure: MM5rInOGfBwf8Or+aO07u79PX/wWNb/Ry+Q5TTObcqoBdEVatkRcdXAec9ZUgPw5aQD26elO/8FnZ2EnOUEKANMbMUyskw2NXWveQ/yjU5e9Z9sVCO0MGQ3cYWOY2CWOwv6UN0/Ct/hSho4NalLopJTaDl/+h93laJOVSzlbhPx1Xv9yY3raf1sHl5/bQY/1I5ZUOT/7eXXHj88GWeNprlLVDUi2fL/wyJMODrLFeAkI/IqOq11PJoxVykDUg9WKQKB7V7k/3bVQ000EEhmJNYh8DULphZKU7EkF9lhCJZLWkx5Qz42W2o3MJ98Je3+UDVjYnuuSlm34xeWYp+s9cmHWGL7nBFA+LDZrpb88vGmsgCmOdld1IFubDnNiGQmNugjn83hOCkL9A0VIF4e8O9weA1pbLXZsb26xwtUP5YyMfW8VrZKfqkfHi8dfNykrqgopoeBbI/jcOMs8HjcVo3VhMkm7vX22S2hPRJtBGjPzkKqVwDcTZ5QUA13SndH6DPGZgZRvFf8vVbszqlcwHUkiVryy47u7aN7CGurVdZE4AVbxR0qIpPp9E4wrxmbzvOVeglm5zUy4eGyt9+ZRTMeQ97I95aY+IPfDZ2XPyWD9HPLztRiJvSKfHAux10r0rqj57K5Hviq1OMyb3cn5aOw15BoBWlSuYxa5uBu03JA=
  - secure: NMW2zftsTWvdVeU/g2ozBE3cwlRIBm1uSM8n4IFrvR4Atv9hEpThqZhsyiX0XjJhdL1i849zwuh6WCAGTcg+SAvcKzewZDGNHkK9hIy+NB/VjccK3sya9YytYBJ7XZv6IvrsS9r80vlwyQ5hoqDMef9oX2Fmms7er7tlvT8xbeXE28mQyBPt/pk8p9kTmESVQl2kuAj6tMAXv9R602M0vVb23Jq3PpVr9qJBlNpNECmGUHFxDeG6PBSn1CiEXQ+ehRDKJRyM19GyQ/RId9J7FaaynmloW7tsR+8p68+LQAsokinoBNCUSPFSX6bpIsigdKangdRjD2B0e/Ehbsk4L4AWPxITGBSrMcrABMZruqLYpppvAIiobcxNodAB4DhtmcrhHVNRI1TF0YNUC1v4/0FHrsZVVeYYjJJrwl9Bf8lnvrXuK3+lW2NNmOwqt0h9GVO02vMTPZfHumeZ89j1HJbb689ieKpRB8W+yyvLd3DQRHQdt4N5aCcirkF0LMWyZ11STYdaJRT9O+NPbPkayqnKoFUi1wx9YrMfO4glisjMEaEdf9WvHD82B8+YvKXS7mO3JcBRv6hgrDj2vYhfxYca4WuD06rcxNJVieJ/HKZHRq+EOTPnAMANJa8XcYKlKPag7TvIh2MsXw2NYC1nlwF+jxFYtdZxrBM7xrc1Nxw=
  - secure: bG5YV/1u5t/FFC4xJLTp7zzSdntJ3Y2RHWS1NK17XU+RxLcZCCOe19W/GmzZDf7AQt7tKAcAeF5SGtuc5rkOLskWYBslg95w11/RSVQCk2wKJ7eVjWgICeIfPiGnC44yMxoTgHKUqT+VxCes8v7XgMuFIPeFEei9RTVRFzEUlbj92QCK5VTmfpTDApc+dKw5lZ4vIGKeh97B6EG9tjf1SfrBZBmfVrebWTi7f5m3WgzZ3iiflWb3qMsOHRRkSYigdJPZ5wkuUszoZpG+zTtByBT+GfdQR96KaB6W3OFTfL/T9mNU67885T6EfdBmH/9eI0oRhL2RcZJGzzu6HHAs6zp6X3U1JbaP7TbTymykcBJmKqwA0/MmHLwkmRIMyS7QM9filU2oWpukIimojfBvxJ1X+f/y5z4A5D1vZLXanz36WpuulFvylKDK93s3LySkRkWgHkoQCT9h7O64kH6p5Yh3IJZUW77Mv//2+cECbngOx4ox6q2Pftkl3VVf/Zteei89QCCNXB0zMMS6lhiv2zOFf1bKy5H7RD2b68CjZQa415Co7Ind4yWr43T2GoVTQDEKdSL94F0C3G0jKZWNvF50wfJqRMz1AV62c4wQiV29MFtvDBSFV8z9Zx9yX01T3L8aDEI6JTtog78ztPwfZtUuNHY4ku0bhIBy4ZReL0Y=
  - secure: ftR2s0eS15yrRvHptkKa4rXXLxZd3y4E1ikHk+IP1zIjXYvyDKduQg2VbhQbIWhostniMsk6NeIWd+qfdqQz4JMMvPGRJ1dYiHcRAulrrOA288fjz+j5WxKbDSxHAe1KZjkaebK+VYMvtCOxTHg6eX+Udwmj6JTKTcdjGNtDCKNpwpAcb/kacN5UOAAMr5mT9cpQ8Y8TbN3pO9vp2QT6LDFXD5hz2AcPpgjG3BZtk2Ac6Z9x0BHKF4kp2CpPr4tjs25YlbkbQXCfo4Mdn9ODCzDCOiqNcT+1P7nkqdNnVJSzSms0XL7862RLEMln39S1xXV8ff2mz8Txp0uWyxWI+mszJVlKtuWAs014tkMj/h9vlhnl+sGJMuK9FlSax69YfWpfoIhnfvO6eIdCrw02LG8I/EHq20uLYKj3IDkWNIreqdvu+ZwKGatArtQk1n/wr+GKqZKcDv2DbcTi3VZoXaqePCDUbihN3ps2ynP+oUWvNmpCz0nlz3QyIFyS3xIMODOjDRCAicjumiA1CnjSavIesttgP9ET0YUaejXyjEGm/xCQbtaNsooabS3canfjXdp8iDxdBc3xhQ1k63EtKbKqGdw/20zBMzaNE6GCtm8myafLDIr6XBCwse24JHEErPNjRjtsCYeCECY6CQSJmutIt/q7eoOZEgt/YgctlpY=
jobs:
  include:
    - stage: Unit Tests, Metalinter, Sonar
      go:
        - 1.14.x
      os:
        - linux
      before_script:
        - echo "dependencies install"
        - env GO111MODULE=off
        - make dependencies
      script:
        - echo "Run unit tests..."
        - env GO111MODULE=on
        - go test -v -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out -json ./... > tests.out
        - make lint-ci
        - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ${COVERALLS_TOKEN}
        - sonar-scanner -Dsonar.projectVersion=${TRAVIS_TAG}
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: Build Application
      go:
        - 1.14.x
      os:
        - linux
      go_import_path: github.com/oleg-balunenko/scrum-report
      script:
        - echo "Build stage"
        - make compile
      after_success:
      deploy:
        skip_cleanup: true
        provider: script
        script: make release
        on:
          tags: true
          condition: "$TRAVIS_OS_NAME = linux"
      addons:
      ssh_known_hosts: github.com
