version: "3.7"
services:
  scrum-report:
    restart: unless-stopped
    container_name: scrum-report
    networks:
      - scrumreport_dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SCRUM_REPORT_PORT: "8080"
      SCRUM_REPORT_LOG_LEVEL: "DEBUG"
    ports:
    - "8080:8080"

networks:
  scrumreport_dev:
    driver: bridge